version: '3.5'

services:
  db:
    image: postgres:12
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped

  frontend:
    container_name: angular_frontend
    ports:
      - "4201:4201"
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
       - ./frontend:/usr/src/app
       - /usr/src/app/node_modules
    restart: unless-stopped

  backend:
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./.env:/.env:ro
    #environment:
      #- SERVER_NAME=${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      #- SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  cron:
    container_name: cron_backend
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./.env:/.env:ro
    build:
      context: ./backend
      dockerfile: cron.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    restart: unless-stopped

volumes:
    postgres:
    pgadmin: