version: "3.5"

services:
  backend:
    volumes:
      - ./.env:/.env
      - ./startup.sh:/startup.sh
      - ./app:/app
      - ./alembic:/alembic
      - ./poetry.lock:/poetry.lock
      - ./pyproject.toml:/pyproject.toml
    build:
      context: ./
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
  cron:
    volumes:
      - ./app:/app
      - ./app/tasks.py:/app/tasks.py:ro
