version: '3.5'

services:
  db:
    image: postgres:12
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres::/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped
  
  backend:
    container_name: fastapi_backend
    ports:
      - "8888:8888"
    volumes: # Only in test/development mode
      - ./backend/app:/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: /app/startup.sh

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: