"""empty message

Revision ID: 3d8172c987c7
Revises: 6f8a507cbf87
Create Date: 2021-12-14 22:30:53.350495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8172c987c7'
down_revision = '6f8a507cbf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('first_name_tutor', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name_tutor', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_column('user', 'last_name_tutor')
    op.drop_column('user', 'first_name_tutor')
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
