"""empty message

Revision ID: 591bfba1b0ad
Revises: 1d0ba06f8dc4
Create Date: 2021-12-18 13:50:39.038210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591bfba1b0ad'
down_revision = '1d0ba06f8dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('current_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'current_state')
    # ### end Alembic commands ###
