"""empty message

Revision ID: a9435e413254
Revises: 591bfba1b0ad
Create Date: 2021-12-19 00:05:06.090625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9435e413254'
down_revision = '591bfba1b0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_healthinsurance_name', table_name='healthinsurance')
    op.create_index(op.f('ix_healthinsurance_name'), 'healthinsurance', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthinsurance_name'), table_name='healthinsurance')
    op.create_index('ix_healthinsurance_name', 'healthinsurance', ['name'], unique=False)
    # ### end Alembic commands ###
